# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rake secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: 8a6ec81ee8b4f2594137e5597cac4e54da29c75ded80ace8bed3d1e72152186181ba468abd0b0e22347fb77400c81773bbde939c66c94d72cfa00db8b97105cb

test:
  secret_key_base: f488a47aee2ca3681e8682fe5eb61b39ecf1f21bd39c5677e89879fa4d9af39299b77a53a0b1054aa4fe32aac54056b1678c78a89febf992fe626853cdf25d0d

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
